//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhantomNet.Blog {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhantomNet.Blog.Logic.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Article URL friendly title &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateArticleUrlFriendlyTitle {
            get {
                return ResourceManager.GetString("DuplicateArticleUrlFriendlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Blogger URL friendly pen name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateBloggerUrlFriendlyPenName {
            get {
                return ResourceManager.GetString("DuplicateBloggerUrlFriendlyPenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Category URL friendly name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateCategoryUrlFriendlyName {
            get {
                return ResourceManager.GetString("DuplicateCategoryUrlFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Article URL friendly title &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidArticleUrlFriendlyTitle {
            get {
                return ResourceManager.GetString("InvalidArticleUrlFriendlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Blogger URL friendly pen name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidBloggerUrlFriendlyPenName {
            get {
                return ResourceManager.GetString("InvalidBloggerUrlFriendlyPenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Category URL friendly name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidCategoryUrlFriendlyName {
            get {
                return ResourceManager.GetString("InvalidCategoryUrlFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type {0} must derive from {1}&lt;{2}, {3}&gt;..
        /// </summary>
        public static string InvalidManagerType {
            get {
                return ResourceManager.GetString("InvalidManagerType", resourceCulture);
            }
        }
    }
}
